### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by redKOTik** [redKOTik/fsd-frontend-second-task#1]
Необходимо более подробно описать ридми, добавить команды для:

- клонирования репозитория
- установки зависимостей
- запуска дев мода
- запуска сборки билда
- развертывания проекта на GitHub Pages

И в целом подогнать ридми под стандарты [тык](https://github.com/fullstack-development/front-end-best-practices/blob/master/Initiation.md#1)

**Comment by redKOTik** [comment]
Исправлено. [Коммит](https://github.com/redKOTik/fsd-frontend-second-task/commit/9ee7db215b1bdde8f25c74ce5e6e143cce7c9ee6)

**Comment by Feinminen** [comment]
Всё ок, можешь закрывать :)
