### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by redKOTik** [redKOTik/fsd-frontend-second-task#2]
Слей все ветки в мастер, пожалуйста, а то сейчас при клонировании просто пустой проект с ридми :)

**Comment by redKOTik** [comment]
Исправлено. [Коммит](https://github.com/redKOTik/fsd-frontend-second-task/commit/d9ecb49e350ff582ed863b83cb7c1521ba7e646c)

**Comment by Feinminen** [comment]
Всё ок, можешь закрывать :)
