### ISSUE TITLE
es-lint

### ISSUE THREAD

**Issue by redKOTik** [redKOTik/fsd-frontend-second-task#4]
Сейчас в проекте много мелких недочётов, вроде отсутствия точек с запятыми, 'trailing comma', наличия 'trailing spaces' и т.д.
Всё это крайне легко правится с помощью линтера(eslint), можно юзать конфиг от airbnb, т.к. у нас стандарты очень похожи.

**Comment by Feinminen** [comment]
Тоже всё ок, можешь закрывать
